import openai
import os

# Load the API key from the environment
openai.api_key = os.getenv("OPENAI_API_KEY")

def query_openai(extracted_text, query):
    prompt = f"Answer the following question based on the provided document text:\n\n{extracted_text}\n\nQuestion: {query}\nAnswer:"

    # Using the new format for OpenAI API (v1.0.0+)
    response = openai.completions.create(
        model="gpt-3.5-turbo",  # or any available model of your choice
        prompt=prompt,
        max_tokens=150
    )

    # Return the response generated by the model
    return response['choices'][0]['text'].strip()
